// Line 1
// Line 2
// Line 3
// Line 4
// Line 5
// Line 6
// @autogenerated
console.log("This file contains @autogenerated on line 7.");
console.log("With the default maxSearchLines=5, this file will NOT be detected as generated.");
